esphome:
  name: esp32c3-btproxy
  name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

esp32:
  variant: ESP32C3
  board: airm2m_core_esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

logger:
api:

# Change the WiFi config to a non-static IP if needed
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 19.7dB
  fast_connect: true
  ap:
    password: "12345678"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 120s

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 1300ms
    window: 1300ms
