## 小米/hass 开关状态桥接器 用于双端同步状态, 可作为寄存器使用

### 小米模组io口定义
## GND: 1, 24, 26, VCC: 14, 26
## 输入按键1-4: 4, 3, 2, 33 // C3  19(GPIO2),20(GPIO3),21(GPIO10),22(GPIO6)
## 输出继电器1-4: 5, 6, 7, 8 // C3  27(GPIO5), 28(GPIO4), 29(GPIO08), 30(GPIO09) 
## reset: 开关任意按键快按三次，再长按 5S 以上，进入清网状态；所有按键指示灯快闪 5 下表示重置成功 （2Hz 频率）
# 1,24,26: GND
# 14,26: 电源3.3v
# pin24: gpio11 VDD_SPI 供电
# todo gpio02 是启动控制引脚, 需替换掉

# 继电器状态读取, 状态翻转短按开关50ms

esphome:
  name: esp32c3-gpio-sensor
  name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

esp32:
  variant: ESP32C3
  board: airm2m_core_esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

logger:
api:
ota:

button:
  - platform: safe_mode
    name: ${display_name} (Safe Mode)

# Change the WiFi config to a non-static IP if needed
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 19dB
  fast_connect: true
  ap:
    password: "12345678"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 120s

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    active: true
    # interval: 1300ms
    # window: 1300ms

# Example configuration entry
binary_sensor:
  - platform: gpio
    pin: GPIO02
    name: "sensor01"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO03
    name: "sensor02"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO10
    name: "sensor03"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO06
    name: "sensor04"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO07
    name: "sensor05"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO11
    name: "sensor06"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO05
    name: "sensor07"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO04
    name: "sensor08"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO08
    name: "sensor09"
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: GPIO09
    name: "sensor10"
    filters:
      - delayed_on: 10ms

