esphome:
  name: esp32c3-btproxy
  name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

esp32:
  variant: ESP32C3
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

logger:
api:
ota:

button:
  - platform: safe_mode
    name: ${display_name} (Safe Mode)

# Change the WiFi config to a non-static IP if needed
wifi:
  ssid: InfoQ-IoT
  password: tian1991
  output_power: 19dB
  fast_connect: true

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 120s
  - platform: status
    name: "ESP32 Node Status"

bluetooth_proxy:
  active: true