esphome:
  name: esp32c3-gateway
  name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

external_components:
  - source: github://myhomeiot/esphome-components

esp32:
  variant: ESP32C3
  board: airm2m_core_esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

logger:
api:
captive_portal:

# Change the WiFi config to a non-static IP if needed
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 19.7dB
  fast_connect: true
  ap:
    password: "12345678"

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO08
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "My Light"


sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 120s

# proxy all
esp32_ble_tracker:
  on_ble_advertise:
    then:
      - homeassistant.event:
          event: esphome.on_ble_advertise
          data:
            packet: !lambda return ble_gateway::BLEGateway::scan_result_to_hci_packet_hex(x.get_scan_result());
            gateway_id: ${device_id}
            proxy: !lambda return true;
