## 小米/hass 开关状态桥接器 用于双端同步状态, 可作为寄存器使用

esphome:
  name: esp32c3-gpio-sensor
  # name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

esp32:
  variant: ESP32C3
  board: airm2m_core_esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

api:
web_server:
  port: 80
  ota: true
ota:
  - platform: esphome
    password: 123456

captive_portal:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # output_power: 19.0dB
  fast_connect: true
  ap:
    password: "12345678"

i2c:
  id: bus_a
  sda: GPIO04
  scl: GPIO05
  frequency: 200kHz
  scan: true

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 120s
  - platform: adc
    pin: GPIO02
    name: "adc01"
  - platform: aht10
    variant: AHT10
    i2c_id: bus_a
    temperature:
      name: "AHT10 Temperature"
    humidity:
      name: "AHT10 Humidity"
    update_interval: 90s

# bluetooth_proxy:
#   active: true

# esp32_ble_tracker:
#   scan_parameters:
#     active: true
#     # interval: 1300ms
#     # window: 1300ms

# Example configuration entry
binary_sensor:
  - platform: gpio
    pin: GPIO00
    name: "sensor01"
    filters:
      - delayed_on: 20ms
  - platform: gpio
    pin: GPIO01
    name: "sensor02"
    filters:
      - delayed_on: 20ms
  - platform: gpio
    pin: GPIO18
    name: "sensor03"
    filters:
      - delayed_on: 20ms
  - platform: gpio
    pin: GPIO19
    name: "sensor04"
    filters:
      - delayed_on: 20ms
  - platform: gpio
    pin: GPIO06
    name: "radar state"
    filters:
      - delayed_on: 20ms
