
## 人在传感器
## 串口方式接入,能读取到门能量,可以自己实现template判断人在状态

esphome:
  name: presense
  name_add_mac_suffix: true

esp8266:
  board: esp01_1m
  framework:
    version: recommended

api:
captive_portal:
logger:
  baud_rate: 0 # 和 UART 冲突，关闭日志
ota:
  - platform: esphome
    password: 123456
web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 19.8dB
  fast_connect: true
  ap:
    password: "12345678"

status_led:
  pin: GPIO2

uart:
  rx_pin:
    number: GPIO3 
  tx_pin: 
    number: GPIO1 
  baud_rate: 9600

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_sensor
    update_interval: 15s
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy