esphome:
  name: esp32c3-switch
  name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

esp32:
  variant: ESP32C3
  board: airm2m_core_esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

api:
web_server:
  port: 80
ota:
  - platform: esphome
    password: 123456

captive_portal:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # output_power: 19.0dB
  fast_connect: true
  ap:
    password: "12345678"

switch:
  - platform: gpio
    pin: GPIO1
    name: "Switch1"
    inverted: true
    id: esp_switch_01
  - platform: gpio
    pin: GPIO0
    name: "Switch2"
    inverted: true
    id: esp_switch_02

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: "Toggle Button"
    on_press:
      then:
        - switch.toggle: esp_switch_02  
    
