name: Build and Publish ESPHome firmware

on:
  workflow_dispatch:
    inputs:
      file:
        description: yaml file name
        required: true
        type: string
      name:
        description: Name of the firmware to publish.
        required: false
        type: string
        default: ESPHome
      esphome_version:
        description: Version of ESPHome to build for.
        required: false
        type: string
        default: latest
      wifi_ssid:
        description: Wifi ssid.
        required: false
        type: string
        default: InfoQ
      wifi_passwd:
        description: Wifi password.
        required: false
        type: string
        default: "12345678"

jobs:
  build:
    name: Build ESPHome binary
    runs-on: ubuntu-latest
    outputs:
      esphome-version: ${{ steps.esphome-build.outputs.esphome-version }}
    steps:
      - uses: actions/checkout@v4
      - name: setting wifi passwd
        env:
          WIFI_SSID: ${{ inputs.wifi_ssid }}
          WIFI_PASSWD: ${{ inputs.wifi_passwd }}
        run: sed "s/WIFI_SSID/$WIFI_SSID/g;s/WIFI_PASSWD/$WIFI_PASSWD/g" secrets.yaml.example > secrets.yaml
      - name: show secrets.yaml
        run: cat secrets.yaml
      - uses: esphome/build-action@v6
        id: esphome-build
        with:
          yaml_file: ${{ inputs.file }}
          version: ${{ inputs.esphome_version }}
      - run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ inputs.name }}
          path: output
